-- MySQL Script generated by MySQL Workbench
-- Wed Jan  6 13:08:14 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema trackstar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trackstar` DEFAULT CHARACTER SET utf8 ;
USE `trackstar` ;

DROP TABLE IF EXISTS `trackstar`.`issues` ;
DROP TABLE IF EXISTS `trackstar`.`projects` ;
DROP TABLE IF EXISTS `trackstar`.`users` ;
-- -----------------------------------------------------
-- Table `trackstar`.`users`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `trackstar`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(64) NOT NULL,
  `password` VARCHAR(64) NOT NULL COMMENT 'Hash value should be inserted',
  `is_active` TINYINT(1) NOT NULL COMMENT '1 means user is active, 0 not',
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;

INSERT INTO `users` (`user_id`,`username`,`password`,`is_active`) VALUES (1,'user1','user1',1), (2,'user2','user2',1), (3,'user3','user3',0);

-- -----------------------------------------------------
-- Table `trackstar`.`projects`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `trackstar`.`projects` (
  `project_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(64) NOT NULL,
  `description` VARCHAR(256) NULL,
  `created_at` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`project_id`),
  CONSTRAINT `fk_projects_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `trackstar`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO projects (project_id, title, description, created_at, user_id) VALUES 
  (1,'Demo App A','Some text',now(),1),
  (2,'Demo App B','Some text text',now(),1),
  (3,'Demo App C','Some text text text',now(),1),
  (4,'Demo App D','Some text text text text',now(),1),
  (5,'Demo App E','Some text text text text text',now(),1),
  (6,'Demo App F','Some text',now(),2),
  (7,'Demo App G','Some text text',now(),2),
  (8,'Demo App H','Some text text text',now(),3),
  (9,'Demo App I','Some text text text text',now(),3);
-- -----------------------------------------------------
-- Table `trackstar`.`issues`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `trackstar`.`issues` (
  `issue_id` INT NOT NULL AUTO_INCREMENT,
  `category` ENUM('ticket', 'feature', 'task') NOT NULL,
  `description` VARCHAR(512) NULL,
  `created_at` DATETIME NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`issue_id`),
  CONSTRAINT `fk_issues_projects`
    FOREIGN KEY (`project_id`)
    REFERENCES `trackstar`.`projects` (`project_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

INSERT INTO `issues` (`category`,`description`,`created_at`,`project_id`) VALUES 
('ticket','Login funktioniert nicht',now(),1), 
('ticket','Bei der User-Erstellen-Maske fehlt das Vorname-Feld',now(),1),
('feature','PDF-Export definieren',now(),1),
('task','Steve anrufen',now(),1);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
